Series
it is a dataype.
To convert list,numpy array,dictionary into series.

In [ ]:
import numpy as n
import pandas as p
l1=['x','y','z']
array=n.array([12,15,18])
dict={1:'agna',2:'nidhi',3:'sree'}

In [ ]:
p.Series(data=l1)

0    x
1    y
2    z
dtype: object

In [ ]:
p.Series(data=l1,index=l1)

x    x
y    y
z    z
dtype: object

In [ ]:
p.Series(array,index=l1)

x    12
y    15
z    18
dtype: int64

In [ ]:
p.Series(dict)

1     agna
2    nidhi
3     sree
dtype: object

In [ ]:
s1=p.Series([4,5,6],index=['Thrissur','kollam','kozikode'])
s2=p.Series([5,34,5,6],index=['Thrissur','kochi','kollam','kozikode'])
s1+s2

Thrissur     9.0
kochi        NaN
kollam      10.0
kozikode    12.0
dtype: float64

data frames:collection of numbers of series

In [ ]:
from numpy.random import randn
n.random.seed(116)

In [ ]:
matrix=p.DataFrame(randn(5,4),index='A B C D E'.split(),columns='P Q R S'.split())

In [ ]:
matrix

          P         Q         R         S
A -1.492299 -1.231295 -0.028144 -0.586060
B  0.074709 -0.053600  1.508410 -0.234901
C -0.066998 -0.341679 -0.148050 -0.322241
D  0.378486  1.182658 -0.549166  0.513041
E -0.751109 -0.727147 -0.652408 -0.586584

In [ ]:
matrix['R']

A   -0.028144
B    1.508410
C   -0.148050
D   -0.549166
E   -0.652408
Name: R, dtype: float64

In [ ]:
matrix[['R','S','P']]

          R         S         P
A -0.028144 -0.586060 -1.492299
B  1.508410 -0.234901  0.074709
C -0.148050 -0.322241 -0.066998
D -0.549166  0.513041  0.378486
E -0.652408 -0.586584 -0.751109

Adding new column

In [ ]:
matrix['new']=matrix['S']+matrix['S']
matrix

          P         Q         R         S       new
A -1.492299 -1.231295 -0.028144 -0.586060 -1.172120
B  0.074709 -0.053600  1.508410 -0.234901 -0.469802
C -0.066998 -0.341679 -0.148050 -0.322241 -0.644481
D  0.378486  1.182658 -0.549166  0.513041  1.026081
E -0.751109 -0.727147 -0.652408 -0.586584 -1.173168

In [ ]:
matrix.drop(['new'],axis=1)

          P         Q         R         S
A -1.492299 -1.231295 -0.028144 -0.586060
B  0.074709 -0.053600  1.508410 -0.234901
C -0.066998 -0.341679 -0.148050 -0.322241
D  0.378486  1.182658 -0.549166  0.513041
E -0.751109 -0.727147 -0.652408 -0.586584

In [ ]:
matrix.drop(['new'],axis=1,inplace=True)

In [ ]:
matrix.loc[['A','B']]

          P         Q         R         S
A -1.492299 -1.231295 -0.028144 -0.586060
B  0.074709 -0.053600  1.508410 -0.234901

In [ ]:
matrix.iloc[1,1]

-0.05360043386397779

In [ ]:
matrix.iloc[0]

P   -1.492299
Q   -1.231295
R   -0.028144
S   -0.586060
Name: A, dtype: float64

In [ ]:
matrix.loc['C','P']

-0.06699775463717023

In [ ]:
matrix>0

       P      Q      R      S
A  False  False  False  False
B   True  False   True  False
C  False  False  False  False
D   True   True  False   True
E  False  False  False  False

In [ ]:
matrix[matrix>0]

          P         Q        R         S
A       NaN       NaN      NaN       NaN
B  0.074709       NaN  1.50841       NaN
C       NaN       NaN      NaN       NaN
D  0.378486  1.182658      NaN  0.513041
E       NaN       NaN      NaN       NaN

In [ ]:
matrix

          P         Q         R         S
A -1.492299 -1.231295 -0.028144 -0.586060
B  0.074709 -0.053600  1.508410 -0.234901
C -0.066998 -0.341679 -0.148050 -0.322241
D  0.378486  1.182658 -0.549166  0.513041
E -0.751109 -0.727147 -0.652408 -0.586584

In [ ]:
matrix[matrix['P']>0]

          P         Q         R         S
B  0.074709 -0.053600  1.508410 -0.234901
D  0.378486  1.182658 -0.549166  0.513041

In [ ]:
matrix['Q']>0

A    False
B    False
C    False
D     True
E    False
Name: Q, dtype: bool

In [ ]:
matrix[matrix['P']>0][['S','R']]

          S         R
B -0.234901  1.508410
D  0.513041 -0.549166

In [ ]:
  matrix[(matrix['S']<0)&(matrix['P']>0)]

          P       Q        R         S
B  0.074709 -0.0536  1.50841 -0.234901

In [ ]:
  matrix[(matrix['S']>1)|(matrix['P']>0)]

          P         Q         R         S
B  0.074709 -0.053600  1.508410 -0.234901
D  0.378486  1.182658 -0.549166  0.513041

In [ ]:
import numpy as np
import pandas as pd
df=pd.DataFrame ({'A':[1,2,np.NAN],'B':[5,np.NAN,np.NAN],'C':[1,2,3]})

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df.fillna(value='NULL')

      A     B  C
0     1     5  1
1     2  NULL  2
2  NULL  NULL  3

In [ ]:
df=pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abcd','dfg','ss','ssg']})

In [ ]:
df.head()

   col1  col2  col3
0     1   444  abcd
1     2   555   dfg
2     3   666    ss
3     4   444   ssg

In [ ]:
df['col2'].unique()

array([444, 555, 666])

In [ ]:
df['col2'].nunique()

3

In [ ]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [ ]:
newdf=df[(df['col2']>3)&(df["col2"]==555)]
newdf

   col2 col3
1   555  dfg

In [ ]:
def times2(x):
  return x*2

In [ ]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [ ]:
df['col3'].apply(len)

0    4
1    3
2    2
3    3
Name: col3, dtype: int64

In [ ]:
df['col1'].sum()

10

In [ ]:
del df['col1']
df

   col2  col3
0   444  abcd
1   555   dfg
2   666    ss
3   444   ssg

In [ ]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.sort_values(by='col2')

   col2  col3
0   444  abcd
3   444   ssg
1   555   dfg
2   666    ss

In [ ]:
df.sort_values(by='col2',inplace=True)
df

   col2  col3
0   444  abcd
3   444   ssg
1   555   dfg
2   666    ss

In [ ]:
df.isnull()

    col2   col3
0  False  False
3  False  False
1  False  False
2  False  False